/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HyperScript2 */

#ifndef _Included_HyperScript2
#define _Included_HyperScript2
#ifdef __cplusplus
extern "C" {
#endif
#undef HyperScript2_FOCUS_TRAVERSABLE_UNKNOWN
#define HyperScript2_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef HyperScript2_FOCUS_TRAVERSABLE_DEFAULT
#define HyperScript2_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef HyperScript2_FOCUS_TRAVERSABLE_SET
#define HyperScript2_FOCUS_TRAVERSABLE_SET 2L
/* Inaccessible static: focusTraversalKeyPropertyNames */
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef HyperScript2_TOP_ALIGNMENT
#define HyperScript2_TOP_ALIGNMENT 0.0f
#undef HyperScript2_CENTER_ALIGNMENT
#define HyperScript2_CENTER_ALIGNMENT 0.5f
#undef HyperScript2_BOTTOM_ALIGNMENT
#define HyperScript2_BOTTOM_ALIGNMENT 1.0f
#undef HyperScript2_LEFT_ALIGNMENT
#define HyperScript2_LEFT_ALIGNMENT 0.0f
#undef HyperScript2_RIGHT_ALIGNMENT
#define HyperScript2_RIGHT_ALIGNMENT 1.0f
#undef HyperScript2_serialVersionUID
#define HyperScript2_serialVersionUID -7644114512714619750i64
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseWheelListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
#undef HyperScript2_serialVersionUID
#define HyperScript2_serialVersionUID 4613797578919906343i64
/* Inaccessible static: dbg */
#undef HyperScript2_INCLUDE_SELF
#define HyperScript2_INCLUDE_SELF 1L
#undef HyperScript2_SEARCH_HEAVYWEIGHTS
#define HyperScript2_SEARCH_HEAVYWEIGHTS 1L
/* Inaccessible static: class_00024java_00024awt_00024Container */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ContainerListener */
/* Inaccessible static: nameCounter */
#undef HyperScript2_serialVersionUID
#define HyperScript2_serialVersionUID -2728009084054400034i64
#undef HyperScript2_serialVersionUID
#define HyperScript2_serialVersionUID -5836846270535785031i64
/* Inaccessible static: array_00024Ljava_00024lang_00024String */
/*
 * Class:     HyperScript2
 * Method:    initJNI
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_HyperScript2_initJNI
  (JNIEnv *, jobject);

/*
 * Class:     HyperScript2
 * Method:    hs
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HyperScript2_hs
  (JNIEnv *, jobject, jstring);

/*
 * Class:     HyperScript2
 * Method:    connectLoopback
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_HyperScript2_connectLoopback
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     HyperScript2
 * Method:    closeLoopback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HyperScript2_closeLoopback
  (JNIEnv *, jobject);

/*
 * Class:     HyperScript2
 * Method:    readLoopback
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_HyperScript2_readLoopback
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     HyperScript2
 * Method:    writeLoopback
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_HyperScript2_writeLoopback
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
